// Generated by gencpp from file turtlesim_servo/camera_cmd.msg
// DO NOT EDIT!


#ifndef TURTLESIM_SERVO_MESSAGE_CAMERA_CMD_H
#define TURTLESIM_SERVO_MESSAGE_CAMERA_CMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlesim_servo
{
template <class ContainerAllocator>
struct camera_cmd_
{
  typedef camera_cmd_<ContainerAllocator> Type;

  camera_cmd_()
    : dx(0)
    , dy(0)  {
    }
  camera_cmd_(const ContainerAllocator& _alloc)
    : dx(0)
    , dy(0)  {
  (void)_alloc;
    }



   typedef int64_t _dx_type;
  _dx_type dx;

   typedef int64_t _dy_type;
  _dy_type dy;




  typedef boost::shared_ptr< ::turtlesim_servo::camera_cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlesim_servo::camera_cmd_<ContainerAllocator> const> ConstPtr;

}; // struct camera_cmd_

typedef ::turtlesim_servo::camera_cmd_<std::allocator<void> > camera_cmd;

typedef boost::shared_ptr< ::turtlesim_servo::camera_cmd > camera_cmdPtr;
typedef boost::shared_ptr< ::turtlesim_servo::camera_cmd const> camera_cmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlesim_servo::camera_cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlesim_servo::camera_cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtlesim_servo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'turtlesim_servo': ['/home/shengjian/bulldog_ws/src/turtlesim_servo/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim_servo::camera_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim_servo::camera_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlesim_servo::camera_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlesim_servo::camera_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim_servo::camera_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim_servo::camera_cmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlesim_servo::camera_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7ef4e60c6cfeeb3cc8c318b8e4ff545a";
  }

  static const char* value(const ::turtlesim_servo::camera_cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7ef4e60c6cfeeb3cULL;
  static const uint64_t static_value2 = 0xc8c318b8e4ff545aULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlesim_servo::camera_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlesim_servo/camera_cmd";
  }

  static const char* value(const ::turtlesim_servo::camera_cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlesim_servo::camera_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 dx\n\
int64 dy\n\
";
  }

  static const char* value(const ::turtlesim_servo::camera_cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlesim_servo::camera_cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dx);
      stream.next(m.dy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct camera_cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlesim_servo::camera_cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlesim_servo::camera_cmd_<ContainerAllocator>& v)
  {
    s << indent << "dx: ";
    Printer<int64_t>::stream(s, indent + "  ", v.dx);
    s << indent << "dy: ";
    Printer<int64_t>::stream(s, indent + "  ", v.dy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLESIM_SERVO_MESSAGE_CAMERA_CMD_H
