// Generated by gencpp from file turtlesim_servo/turtle_pose_msg.msg
// DO NOT EDIT!


#ifndef TURTLESIM_SERVO_MESSAGE_TURTLE_POSE_MSG_H
#define TURTLESIM_SERVO_MESSAGE_TURTLE_POSE_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlesim_servo
{
template <class ContainerAllocator>
struct turtle_pose_msg_
{
  typedef turtle_pose_msg_<ContainerAllocator> Type;

  turtle_pose_msg_()
    : turtle_pose_x(0.0)
    , turtle_pose_y(0.0)
    , turtle_angle(0.0)  {
    }
  turtle_pose_msg_(const ContainerAllocator& _alloc)
    : turtle_pose_x(0.0)
    , turtle_pose_y(0.0)
    , turtle_angle(0.0)  {
  (void)_alloc;
    }



   typedef float _turtle_pose_x_type;
  _turtle_pose_x_type turtle_pose_x;

   typedef float _turtle_pose_y_type;
  _turtle_pose_y_type turtle_pose_y;

   typedef float _turtle_angle_type;
  _turtle_angle_type turtle_angle;




  typedef boost::shared_ptr< ::turtlesim_servo::turtle_pose_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlesim_servo::turtle_pose_msg_<ContainerAllocator> const> ConstPtr;

}; // struct turtle_pose_msg_

typedef ::turtlesim_servo::turtle_pose_msg_<std::allocator<void> > turtle_pose_msg;

typedef boost::shared_ptr< ::turtlesim_servo::turtle_pose_msg > turtle_pose_msgPtr;
typedef boost::shared_ptr< ::turtlesim_servo::turtle_pose_msg const> turtle_pose_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlesim_servo::turtle_pose_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlesim_servo::turtle_pose_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtlesim_servo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'turtlesim_servo': ['/home/shengjian/bulldog_ws/src/turtlesim_servo/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim_servo::turtle_pose_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim_servo::turtle_pose_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlesim_servo::turtle_pose_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlesim_servo::turtle_pose_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim_servo::turtle_pose_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim_servo::turtle_pose_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlesim_servo::turtle_pose_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81f7be54382f129dc66db0841b93073e";
  }

  static const char* value(const ::turtlesim_servo::turtle_pose_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81f7be54382f129dULL;
  static const uint64_t static_value2 = 0xc66db0841b93073eULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlesim_servo::turtle_pose_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlesim_servo/turtle_pose_msg";
  }

  static const char* value(const ::turtlesim_servo::turtle_pose_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlesim_servo::turtle_pose_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 turtle_pose_x\n\
float32 turtle_pose_y\n\
float32 turtle_angle\n\
";
  }

  static const char* value(const ::turtlesim_servo::turtle_pose_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlesim_servo::turtle_pose_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.turtle_pose_x);
      stream.next(m.turtle_pose_y);
      stream.next(m.turtle_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct turtle_pose_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlesim_servo::turtle_pose_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlesim_servo::turtle_pose_msg_<ContainerAllocator>& v)
  {
    s << indent << "turtle_pose_x: ";
    Printer<float>::stream(s, indent + "  ", v.turtle_pose_x);
    s << indent << "turtle_pose_y: ";
    Printer<float>::stream(s, indent + "  ", v.turtle_pose_y);
    s << indent << "turtle_angle: ";
    Printer<float>::stream(s, indent + "  ", v.turtle_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLESIM_SERVO_MESSAGE_TURTLE_POSE_MSG_H
