// Generated by gencpp from file turtlesim_servo/turtle_cmd.msg
// DO NOT EDIT!


#ifndef TURTLESIM_SERVO_MESSAGE_TURTLE_CMD_H
#define TURTLESIM_SERVO_MESSAGE_TURTLE_CMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlesim_servo
{
template <class ContainerAllocator>
struct turtle_cmd_
{
  typedef turtle_cmd_<ContainerAllocator> Type;

  turtle_cmd_()
    : acc(0.0)
    , d_angle(0.0)  {
    }
  turtle_cmd_(const ContainerAllocator& _alloc)
    : acc(0.0)
    , d_angle(0.0)  {
  (void)_alloc;
    }



   typedef float _acc_type;
  _acc_type acc;

   typedef float _d_angle_type;
  _d_angle_type d_angle;




  typedef boost::shared_ptr< ::turtlesim_servo::turtle_cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlesim_servo::turtle_cmd_<ContainerAllocator> const> ConstPtr;

}; // struct turtle_cmd_

typedef ::turtlesim_servo::turtle_cmd_<std::allocator<void> > turtle_cmd;

typedef boost::shared_ptr< ::turtlesim_servo::turtle_cmd > turtle_cmdPtr;
typedef boost::shared_ptr< ::turtlesim_servo::turtle_cmd const> turtle_cmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlesim_servo::turtle_cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlesim_servo::turtle_cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtlesim_servo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'turtlesim_servo': ['/home/shengjian/bulldog_ws/src/turtlesim_servo/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim_servo::turtle_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim_servo::turtle_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlesim_servo::turtle_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlesim_servo::turtle_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim_servo::turtle_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim_servo::turtle_cmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlesim_servo::turtle_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6c9aabef2c9a5b6c2f5599cd4f73216";
  }

  static const char* value(const ::turtlesim_servo::turtle_cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6c9aabef2c9a5b6ULL;
  static const uint64_t static_value2 = 0xc2f5599cd4f73216ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlesim_servo::turtle_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlesim_servo/turtle_cmd";
  }

  static const char* value(const ::turtlesim_servo::turtle_cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlesim_servo::turtle_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 acc\n\
float32 d_angle\n\
";
  }

  static const char* value(const ::turtlesim_servo::turtle_cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlesim_servo::turtle_cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.acc);
      stream.next(m.d_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct turtle_cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlesim_servo::turtle_cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlesim_servo::turtle_cmd_<ContainerAllocator>& v)
  {
    s << indent << "acc: ";
    Printer<float>::stream(s, indent + "  ", v.acc);
    s << indent << "d_angle: ";
    Printer<float>::stream(s, indent + "  ", v.d_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLESIM_SERVO_MESSAGE_TURTLE_CMD_H
