// Generated by gencpp from file gpd/detect_graspsResponse.msg
// DO NOT EDIT!


#ifndef GPD_MESSAGE_DETECT_GRASPSRESPONSE_H
#define GPD_MESSAGE_DETECT_GRASPSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <gpd/GraspConfigList.h>

namespace gpd
{
template <class ContainerAllocator>
struct detect_graspsResponse_
{
  typedef detect_graspsResponse_<ContainerAllocator> Type;

  detect_graspsResponse_()
    : grasp_configs()  {
    }
  detect_graspsResponse_(const ContainerAllocator& _alloc)
    : grasp_configs(_alloc)  {
  (void)_alloc;
    }



   typedef  ::gpd::GraspConfigList_<ContainerAllocator>  _grasp_configs_type;
  _grasp_configs_type grasp_configs;




  typedef boost::shared_ptr< ::gpd::detect_graspsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gpd::detect_graspsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct detect_graspsResponse_

typedef ::gpd::detect_graspsResponse_<std::allocator<void> > detect_graspsResponse;

typedef boost::shared_ptr< ::gpd::detect_graspsResponse > detect_graspsResponsePtr;
typedef boost::shared_ptr< ::gpd::detect_graspsResponse const> detect_graspsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gpd::detect_graspsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gpd::detect_graspsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gpd

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'gpd': ['/home/shengjian/bulldog_ws/src/gpd/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gpd::detect_graspsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gpd::detect_graspsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gpd::detect_graspsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gpd::detect_graspsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gpd::detect_graspsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gpd::detect_graspsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gpd::detect_graspsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "41ffbce4bfeb01a8a6398948862ba5d0";
  }

  static const char* value(const ::gpd::detect_graspsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x41ffbce4bfeb01a8ULL;
  static const uint64_t static_value2 = 0xa6398948862ba5d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::gpd::detect_graspsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gpd/detect_graspsResponse";
  }

  static const char* value(const ::gpd::detect_graspsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gpd::detect_graspsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gpd/GraspConfigList grasp_configs\n\
\n\
\n\
================================================================================\n\
MSG: gpd/GraspConfigList\n\
# This message stores a list of grasp configurations.\n\
\n\
# The time of acquisition, and the coordinate frame ID.\n\
Header header\n\
\n\
# The list of grasp configurations.\n\
gpd/GraspConfig[] grasps\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: gpd/GraspConfig\n\
# This message describes a 2-finger grasp configuration by its 6-DOF pose, \n\
# consisting of a 3-DOF position and 3-DOF orientation, and the opening \n\
# width of the robot hand.\n\
\n\
# Position\n\
geometry_msgs/Point bottom # centered bottom/base of the robot hand)\n\
geometry_msgs/Point top # centered top/fingertip of the robot hand)\n\
geometry_msgs/Point surface # centered position on object surface\n\
\n\
# Orientation represented as three axis (R = [approach binormal axis])\n\
geometry_msgs/Vector3 approach # The grasp approach direction\n\
geometry_msgs/Vector3 binormal # The binormal\n\
geometry_msgs/Vector3 axis # The hand axis\n\
\n\
geometry_msgs/Point sample # Point at which the grasp was found\n\
\n\
std_msgs/Float32 width # Required aperture (opening width) of the robot hand \n\
\n\
std_msgs/Float32 score # Score assigned to the grasp by the classifier\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: std_msgs/Float32\n\
float32 data\n\
";
  }

  static const char* value(const ::gpd::detect_graspsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gpd::detect_graspsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.grasp_configs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct detect_graspsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gpd::detect_graspsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gpd::detect_graspsResponse_<ContainerAllocator>& v)
  {
    s << indent << "grasp_configs: ";
    s << std::endl;
    Printer< ::gpd::GraspConfigList_<ContainerAllocator> >::stream(s, indent + "  ", v.grasp_configs);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GPD_MESSAGE_DETECT_GRASPSRESPONSE_H
