// Generated by gencpp from file gpd/detect_grasps.msg
// DO NOT EDIT!


#ifndef GPD_MESSAGE_DETECT_GRASPS_H
#define GPD_MESSAGE_DETECT_GRASPS_H

#include <ros/service_traits.h>


#include <gpd/detect_graspsRequest.h>
#include <gpd/detect_graspsResponse.h>


namespace gpd
{

struct detect_grasps
{

typedef detect_graspsRequest Request;
typedef detect_graspsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct detect_grasps
} // namespace gpd


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gpd::detect_grasps > {
  static const char* value()
  {
    return "5973d1792c74f9d3213952e5e42396ae";
  }

  static const char* value(const ::gpd::detect_grasps&) { return value(); }
};

template<>
struct DataType< ::gpd::detect_grasps > {
  static const char* value()
  {
    return "gpd/detect_grasps";
  }

  static const char* value(const ::gpd::detect_grasps&) { return value(); }
};


// service_traits::MD5Sum< ::gpd::detect_graspsRequest> should match 
// service_traits::MD5Sum< ::gpd::detect_grasps > 
template<>
struct MD5Sum< ::gpd::detect_graspsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gpd::detect_grasps >::value();
  }
  static const char* value(const ::gpd::detect_graspsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gpd::detect_graspsRequest> should match 
// service_traits::DataType< ::gpd::detect_grasps > 
template<>
struct DataType< ::gpd::detect_graspsRequest>
{
  static const char* value()
  {
    return DataType< ::gpd::detect_grasps >::value();
  }
  static const char* value(const ::gpd::detect_graspsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gpd::detect_graspsResponse> should match 
// service_traits::MD5Sum< ::gpd::detect_grasps > 
template<>
struct MD5Sum< ::gpd::detect_graspsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gpd::detect_grasps >::value();
  }
  static const char* value(const ::gpd::detect_graspsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gpd::detect_graspsResponse> should match 
// service_traits::DataType< ::gpd::detect_grasps > 
template<>
struct DataType< ::gpd::detect_graspsResponse>
{
  static const char* value()
  {
    return DataType< ::gpd::detect_grasps >::value();
  }
  static const char* value(const ::gpd::detect_graspsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GPD_MESSAGE_DETECT_GRASPS_H
