// Generated by gencpp from file gpd/GraspConfig.msg
// DO NOT EDIT!


#ifndef GPD_MESSAGE_GRASPCONFIG_H
#define GPD_MESSAGE_GRASPCONFIG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Point.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>

namespace gpd
{
template <class ContainerAllocator>
struct GraspConfig_
{
  typedef GraspConfig_<ContainerAllocator> Type;

  GraspConfig_()
    : bottom()
    , top()
    , surface()
    , approach()
    , binormal()
    , axis()
    , sample()
    , width()
    , score()  {
    }
  GraspConfig_(const ContainerAllocator& _alloc)
    : bottom(_alloc)
    , top(_alloc)
    , surface(_alloc)
    , approach(_alloc)
    , binormal(_alloc)
    , axis(_alloc)
    , sample(_alloc)
    , width(_alloc)
    , score(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _bottom_type;
  _bottom_type bottom;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _top_type;
  _top_type top;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _surface_type;
  _surface_type surface;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _approach_type;
  _approach_type approach;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _binormal_type;
  _binormal_type binormal;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _axis_type;
  _axis_type axis;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _sample_type;
  _sample_type sample;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _width_type;
  _width_type width;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _score_type;
  _score_type score;




  typedef boost::shared_ptr< ::gpd::GraspConfig_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gpd::GraspConfig_<ContainerAllocator> const> ConstPtr;

}; // struct GraspConfig_

typedef ::gpd::GraspConfig_<std::allocator<void> > GraspConfig;

typedef boost::shared_ptr< ::gpd::GraspConfig > GraspConfigPtr;
typedef boost::shared_ptr< ::gpd::GraspConfig const> GraspConfigConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gpd::GraspConfig_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gpd::GraspConfig_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gpd

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'gpd': ['/home/shengjian/bulldog_ws/src/gpd/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gpd::GraspConfig_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gpd::GraspConfig_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gpd::GraspConfig_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gpd::GraspConfig_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gpd::GraspConfig_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gpd::GraspConfig_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gpd::GraspConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e6b3c31591d4b0fc202f092dca68301";
  }

  static const char* value(const ::gpd::GraspConfig_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e6b3c31591d4b0fULL;
  static const uint64_t static_value2 = 0xc202f092dca68301ULL;
};

template<class ContainerAllocator>
struct DataType< ::gpd::GraspConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gpd/GraspConfig";
  }

  static const char* value(const ::gpd::GraspConfig_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gpd::GraspConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message describes a 2-finger grasp configuration by its 6-DOF pose, \n\
# consisting of a 3-DOF position and 3-DOF orientation, and the opening \n\
# width of the robot hand.\n\
\n\
# Position\n\
geometry_msgs/Point bottom # centered bottom/base of the robot hand)\n\
geometry_msgs/Point top # centered top/fingertip of the robot hand)\n\
geometry_msgs/Point surface # centered position on object surface\n\
\n\
# Orientation represented as three axis (R = [approach binormal axis])\n\
geometry_msgs/Vector3 approach # The grasp approach direction\n\
geometry_msgs/Vector3 binormal # The binormal\n\
geometry_msgs/Vector3 axis # The hand axis\n\
\n\
geometry_msgs/Point sample # Point at which the grasp was found\n\
\n\
std_msgs/Float32 width # Required aperture (opening width) of the robot hand \n\
\n\
std_msgs/Float32 score # Score assigned to the grasp by the classifier\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: std_msgs/Float32\n\
float32 data\n\
";
  }

  static const char* value(const ::gpd::GraspConfig_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gpd::GraspConfig_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bottom);
      stream.next(m.top);
      stream.next(m.surface);
      stream.next(m.approach);
      stream.next(m.binormal);
      stream.next(m.axis);
      stream.next(m.sample);
      stream.next(m.width);
      stream.next(m.score);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GraspConfig_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gpd::GraspConfig_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gpd::GraspConfig_<ContainerAllocator>& v)
  {
    s << indent << "bottom: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.bottom);
    s << indent << "top: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.top);
    s << indent << "surface: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.surface);
    s << indent << "approach: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.approach);
    s << indent << "binormal: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.binormal);
    s << indent << "axis: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.axis);
    s << indent << "sample: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.sample);
    s << indent << "width: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.width);
    s << indent << "score: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.score);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GPD_MESSAGE_GRASPCONFIG_H
