(cl:in-package robotiq_s_model_articulated_msgs-msg)
(cl:export '(RACT-VAL
          RACT
          RMOD-VAL
          RMOD
          RGTO-VAL
          RGTO
          RATR-VAL
          RATR
          RICF-VAL
          RICF
          RICS-VAL
          RICS
          RPRA-VAL
          RPRA
          RSPA-VAL
          RSPA
          RFRA-VAL
          RFRA
          RPRB-VAL
          RPRB
          RSPB-VAL
          RSPB
          RFRB-VAL
          RFRB
          RPRC-VAL
          RPRC
          RSPC-VAL
          RSPC
          RFRC-VAL
          RFRC
          RPRS-VAL
          RPRS
          RSPS-VAL
          RSPS
          RFRS-VAL
          RFRS
))