(cl:in-package robotiq_s_model_control-msg)
(cl:export '(GACT-VAL
          GACT
          GMOD-VAL
          GMOD
          GGTO-VAL
          GGTO
          GIMC-VAL
          GIMC
          GSTA-VAL
          GSTA
          GDTA-VAL
          GDTA
          GDTB-VAL
          GDTB
          GDTC-VAL
          GDTC
          GDTS-VAL
          GDTS
          GFLT-VAL
          GFLT
          GPRA-VAL
          GPRA
          GPOA-VAL
          GPOA
          GCUA-VAL
          GCUA
          GPRB-VAL
          GPRB
          GPOB-VAL
          GPOB
          GCUB-VAL
          GCUB
          GPRC-VAL
          GPRC
          GPOC-VAL
          GPOC
          GCUC-VAL
          GCUC
          GPRS-VAL
          GPRS
          GPOS-VAL
          GPOS
          GCUS-VAL
          GCUS
))