// Generated by gencpp from file mask_rcnn_ros/MaskDetectResponse.msg
// DO NOT EDIT!


#ifndef MASK_RCNN_ROS_MESSAGE_MASKDETECTRESPONSE_H
#define MASK_RCNN_ROS_MESSAGE_MASKDETECTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int64.h>

namespace mask_rcnn_ros
{
template <class ContainerAllocator>
struct MaskDetectResponse_
{
  typedef MaskDetectResponse_<ContainerAllocator> Type;

  MaskDetectResponse_()
    : indices()  {
    }
  MaskDetectResponse_(const ContainerAllocator& _alloc)
    : indices(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::std_msgs::Int64_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::std_msgs::Int64_<ContainerAllocator> >::other >  _indices_type;
  _indices_type indices;




  typedef boost::shared_ptr< ::mask_rcnn_ros::MaskDetectResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mask_rcnn_ros::MaskDetectResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MaskDetectResponse_

typedef ::mask_rcnn_ros::MaskDetectResponse_<std::allocator<void> > MaskDetectResponse;

typedef boost::shared_ptr< ::mask_rcnn_ros::MaskDetectResponse > MaskDetectResponsePtr;
typedef boost::shared_ptr< ::mask_rcnn_ros::MaskDetectResponse const> MaskDetectResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mask_rcnn_ros::MaskDetectResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mask_rcnn_ros::MaskDetectResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mask_rcnn_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'mask_rcnn_ros': ['/home/shengjian/bulldog_ws/src/mask_rcnn_ros/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mask_rcnn_ros::MaskDetectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mask_rcnn_ros::MaskDetectResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mask_rcnn_ros::MaskDetectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mask_rcnn_ros::MaskDetectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mask_rcnn_ros::MaskDetectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mask_rcnn_ros::MaskDetectResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mask_rcnn_ros::MaskDetectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "743d3c632b01d11ccb6b9ca0f7552d8b";
  }

  static const char* value(const ::mask_rcnn_ros::MaskDetectResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x743d3c632b01d11cULL;
  static const uint64_t static_value2 = 0xcb6b9ca0f7552d8bULL;
};

template<class ContainerAllocator>
struct DataType< ::mask_rcnn_ros::MaskDetectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mask_rcnn_ros/MaskDetectResponse";
  }

  static const char* value(const ::mask_rcnn_ros::MaskDetectResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mask_rcnn_ros::MaskDetectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Int64[] indices\n\
\n\
================================================================================\n\
MSG: std_msgs/Int64\n\
int64 data\n\
";
  }

  static const char* value(const ::mask_rcnn_ros::MaskDetectResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mask_rcnn_ros::MaskDetectResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.indices);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MaskDetectResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mask_rcnn_ros::MaskDetectResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mask_rcnn_ros::MaskDetectResponse_<ContainerAllocator>& v)
  {
    s << indent << "indices[]" << std::endl;
    for (size_t i = 0; i < v.indices.size(); ++i)
    {
      s << indent << "  indices[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::Int64_<ContainerAllocator> >::stream(s, indent + "    ", v.indices[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MASK_RCNN_ROS_MESSAGE_MASKDETECTRESPONSE_H
