// Generated by gencpp from file mask_rcnn_ros/MaskDetect.msg
// DO NOT EDIT!


#ifndef MASK_RCNN_ROS_MESSAGE_MASKDETECT_H
#define MASK_RCNN_ROS_MESSAGE_MASKDETECT_H

#include <ros/service_traits.h>


#include <mask_rcnn_ros/MaskDetectRequest.h>
#include <mask_rcnn_ros/MaskDetectResponse.h>


namespace mask_rcnn_ros
{

struct MaskDetect
{

typedef MaskDetectRequest Request;
typedef MaskDetectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MaskDetect
} // namespace mask_rcnn_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mask_rcnn_ros::MaskDetect > {
  static const char* value()
  {
    return "1de517f411134622360bbeab63b02eaa";
  }

  static const char* value(const ::mask_rcnn_ros::MaskDetect&) { return value(); }
};

template<>
struct DataType< ::mask_rcnn_ros::MaskDetect > {
  static const char* value()
  {
    return "mask_rcnn_ros/MaskDetect";
  }

  static const char* value(const ::mask_rcnn_ros::MaskDetect&) { return value(); }
};


// service_traits::MD5Sum< ::mask_rcnn_ros::MaskDetectRequest> should match 
// service_traits::MD5Sum< ::mask_rcnn_ros::MaskDetect > 
template<>
struct MD5Sum< ::mask_rcnn_ros::MaskDetectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mask_rcnn_ros::MaskDetect >::value();
  }
  static const char* value(const ::mask_rcnn_ros::MaskDetectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mask_rcnn_ros::MaskDetectRequest> should match 
// service_traits::DataType< ::mask_rcnn_ros::MaskDetect > 
template<>
struct DataType< ::mask_rcnn_ros::MaskDetectRequest>
{
  static const char* value()
  {
    return DataType< ::mask_rcnn_ros::MaskDetect >::value();
  }
  static const char* value(const ::mask_rcnn_ros::MaskDetectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mask_rcnn_ros::MaskDetectResponse> should match 
// service_traits::MD5Sum< ::mask_rcnn_ros::MaskDetect > 
template<>
struct MD5Sum< ::mask_rcnn_ros::MaskDetectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mask_rcnn_ros::MaskDetect >::value();
  }
  static const char* value(const ::mask_rcnn_ros::MaskDetectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mask_rcnn_ros::MaskDetectResponse> should match 
// service_traits::DataType< ::mask_rcnn_ros::MaskDetect > 
template<>
struct DataType< ::mask_rcnn_ros::MaskDetectResponse>
{
  static const char* value()
  {
    return DataType< ::mask_rcnn_ros::MaskDetect >::value();
  }
  static const char* value(const ::mask_rcnn_ros::MaskDetectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MASK_RCNN_ROS_MESSAGE_MASKDETECT_H
