# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from turtlesim_servo/turtle_pose_msg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class turtle_pose_msg(genpy.Message):
  _md5sum = "81f7be54382f129dc66db0841b93073e"
  _type = "turtlesim_servo/turtle_pose_msg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 turtle_pose_x
float32 turtle_pose_y
float32 turtle_angle"""
  __slots__ = ['turtle_pose_x','turtle_pose_y','turtle_angle']
  _slot_types = ['float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       turtle_pose_x,turtle_pose_y,turtle_angle

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(turtle_pose_msg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.turtle_pose_x is None:
        self.turtle_pose_x = 0.
      if self.turtle_pose_y is None:
        self.turtle_pose_y = 0.
      if self.turtle_angle is None:
        self.turtle_angle = 0.
    else:
      self.turtle_pose_x = 0.
      self.turtle_pose_y = 0.
      self.turtle_angle = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3f.pack(_x.turtle_pose_x, _x.turtle_pose_y, _x.turtle_angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.turtle_pose_x, _x.turtle_pose_y, _x.turtle_angle,) = _struct_3f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3f.pack(_x.turtle_pose_x, _x.turtle_pose_y, _x.turtle_angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.turtle_pose_x, _x.turtle_pose_y, _x.turtle_angle,) = _struct_3f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3f = struct.Struct("<3f")
