#!/usr/bin/env python

import sys
import copy
import rospy
import moveit_commander
import moveit_msgs.msg
import geometry_msgs.msg

print "============ Starting tutorial setup"
moveit_commander.roscpp_initialize(sys.argv)
rospy.init_node('husky_dual_ur5_moveit_tutorial',
                anonymous=True)

robot = moveit_commander.RobotCommander()
scene = moveit_commander.PlanningSceneInterface()
group = moveit_commander.MoveGroupCommander("right_arm")
#display_trajectory_publisher = rospy.Publisher(
#                                    '/move_group/display_planned_path',
#                                    moveit_msgs.msg.DisplayTrajectory)
#print "============ Reference frame: %s" % group.get_planning_frame()
#print "============ Robot Groups:"
#print robot.get_group_names()
#print "============ Generating plan 1"

#pose_target = geometry_msgs.msg.Pose()
#pose_target.orientation.w = 1.0
#group.set_pose_target(pose_target)

plan1 = group.plan({'l_ur5_arm_shoulder_joint: 3.14'})

