// Generated by gencpp from file robotiq_force_torque_sensor/sensor_accessor.msg
// DO NOT EDIT!


#ifndef ROBOTIQ_FORCE_TORQUE_SENSOR_MESSAGE_SENSOR_ACCESSOR_H
#define ROBOTIQ_FORCE_TORQUE_SENSOR_MESSAGE_SENSOR_ACCESSOR_H

#include <ros/service_traits.h>


#include <robotiq_force_torque_sensor/sensor_accessorRequest.h>
#include <robotiq_force_torque_sensor/sensor_accessorResponse.h>


namespace robotiq_force_torque_sensor
{

struct sensor_accessor
{

typedef sensor_accessorRequest Request;
typedef sensor_accessorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sensor_accessor
} // namespace robotiq_force_torque_sensor


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotiq_force_torque_sensor::sensor_accessor > {
  static const char* value()
  {
    return "3432968d93676935641d2adbeeedf719";
  }

  static const char* value(const ::robotiq_force_torque_sensor::sensor_accessor&) { return value(); }
};

template<>
struct DataType< ::robotiq_force_torque_sensor::sensor_accessor > {
  static const char* value()
  {
    return "robotiq_force_torque_sensor/sensor_accessor";
  }

  static const char* value(const ::robotiq_force_torque_sensor::sensor_accessor&) { return value(); }
};


// service_traits::MD5Sum< ::robotiq_force_torque_sensor::sensor_accessorRequest> should match 
// service_traits::MD5Sum< ::robotiq_force_torque_sensor::sensor_accessor > 
template<>
struct MD5Sum< ::robotiq_force_torque_sensor::sensor_accessorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotiq_force_torque_sensor::sensor_accessor >::value();
  }
  static const char* value(const ::robotiq_force_torque_sensor::sensor_accessorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotiq_force_torque_sensor::sensor_accessorRequest> should match 
// service_traits::DataType< ::robotiq_force_torque_sensor::sensor_accessor > 
template<>
struct DataType< ::robotiq_force_torque_sensor::sensor_accessorRequest>
{
  static const char* value()
  {
    return DataType< ::robotiq_force_torque_sensor::sensor_accessor >::value();
  }
  static const char* value(const ::robotiq_force_torque_sensor::sensor_accessorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotiq_force_torque_sensor::sensor_accessorResponse> should match 
// service_traits::MD5Sum< ::robotiq_force_torque_sensor::sensor_accessor > 
template<>
struct MD5Sum< ::robotiq_force_torque_sensor::sensor_accessorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotiq_force_torque_sensor::sensor_accessor >::value();
  }
  static const char* value(const ::robotiq_force_torque_sensor::sensor_accessorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotiq_force_torque_sensor::sensor_accessorResponse> should match 
// service_traits::DataType< ::robotiq_force_torque_sensor::sensor_accessor > 
template<>
struct DataType< ::robotiq_force_torque_sensor::sensor_accessorResponse>
{
  static const char* value()
  {
    return DataType< ::robotiq_force_torque_sensor::sensor_accessor >::value();
  }
  static const char* value(const ::robotiq_force_torque_sensor::sensor_accessorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTIQ_FORCE_TORQUE_SENSOR_MESSAGE_SENSOR_ACCESSOR_H
