# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robotiq_force_torque_sensor/ft_sensor.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ft_sensor(genpy.Message):
  _md5sum = "060fd5fcbaefcff9daec9d5bb2d41714"
  _type = "robotiq_force_torque_sensor/ft_sensor"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 Fx
float32 Fy
float32 Fz
float32 Mx
float32 My
float32 Mz
"""
  __slots__ = ['Fx','Fy','Fz','Mx','My','Mz']
  _slot_types = ['float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Fx,Fy,Fz,Mx,My,Mz

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ft_sensor, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.Fx is None:
        self.Fx = 0.
      if self.Fy is None:
        self.Fy = 0.
      if self.Fz is None:
        self.Fz = 0.
      if self.Mx is None:
        self.Mx = 0.
      if self.My is None:
        self.My = 0.
      if self.Mz is None:
        self.Mz = 0.
    else:
      self.Fx = 0.
      self.Fy = 0.
      self.Fz = 0.
      self.Mx = 0.
      self.My = 0.
      self.Mz = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_6f.pack(_x.Fx, _x.Fy, _x.Fz, _x.Mx, _x.My, _x.Mz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.Fx, _x.Fy, _x.Fz, _x.Mx, _x.My, _x.Mz,) = _struct_6f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_6f.pack(_x.Fx, _x.Fy, _x.Fz, _x.Mx, _x.My, _x.Mz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.Fx, _x.Fy, _x.Fz, _x.Mx, _x.My, _x.Mz,) = _struct_6f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_6f = struct.Struct("<6f")
