# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robotiq_c_model_control/CModel_robot_input.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CModel_robot_input(genpy.Message):
  _md5sum = "17d49e32c00f4f2fb4fe664060553362"
  _type = "robotiq_c_model_control/CModel_robot_input"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 gACT 
uint8 gGTO 
uint8 gSTA 
uint8 gOBJ 
uint8 gFLT
uint8 gPR
uint8 gPO
uint8 gCU
"""
  __slots__ = ['gACT','gGTO','gSTA','gOBJ','gFLT','gPR','gPO','gCU']
  _slot_types = ['uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       gACT,gGTO,gSTA,gOBJ,gFLT,gPR,gPO,gCU

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CModel_robot_input, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.gACT is None:
        self.gACT = 0
      if self.gGTO is None:
        self.gGTO = 0
      if self.gSTA is None:
        self.gSTA = 0
      if self.gOBJ is None:
        self.gOBJ = 0
      if self.gFLT is None:
        self.gFLT = 0
      if self.gPR is None:
        self.gPR = 0
      if self.gPO is None:
        self.gPO = 0
      if self.gCU is None:
        self.gCU = 0
    else:
      self.gACT = 0
      self.gGTO = 0
      self.gSTA = 0
      self.gOBJ = 0
      self.gFLT = 0
      self.gPR = 0
      self.gPO = 0
      self.gCU = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_8B.pack(_x.gACT, _x.gGTO, _x.gSTA, _x.gOBJ, _x.gFLT, _x.gPR, _x.gPO, _x.gCU))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.gACT, _x.gGTO, _x.gSTA, _x.gOBJ, _x.gFLT, _x.gPR, _x.gPO, _x.gCU,) = _struct_8B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_8B.pack(_x.gACT, _x.gGTO, _x.gSTA, _x.gOBJ, _x.gFLT, _x.gPR, _x.gPO, _x.gCU))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.gACT, _x.gGTO, _x.gSTA, _x.gOBJ, _x.gFLT, _x.gPR, _x.gPO, _x.gCU,) = _struct_8B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_8B = struct.Struct("<8B")
